version: '3.8'

services:
  app:
    build: .
    container_name: project
    command: ls -la /usr/src/app/
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: "analytics"
      POSTGRES_USER: "analytics"
      POSTGRES_DB: "game_analytics"
    depends_on:
      - pgdb

  pgdb:
    container_name: pgdb
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "analytics"
      POSTGRES_USER: "analytics"
      POSTGRES_DB: "game_analytics"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
      ports:
          - "9200:9200"
          - "9300:9300"
      environment:
        discovery.type: "single-node"
      depends_on:
          - pgdb

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        - "5671:5672"

  celery:
    container_name: celery
    build: .
    command: celery -A app worker -l INFO
    volumes:
      - .:/usr/src/app
    environment:
        - CELERY_BROKER=amqp://guest@rabbitmq//
        - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
        - redis

#Redis/backend
  redis:
    container_name: redis
    image: 'redis:alpine'

#Tasks admin
  flower:
    container_name: flower
    build: .
    command: celery $my_challenge $tasks flower
    ports:
        - "5556:5555"
    environment:
        - CELERY_BROKER=amqp://guest@rabbitmq//
        - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
        - rabbitmq
        - celery

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A app beat -l INFO
    environment:
        - CELERY_BROKER=amqp://guest@rabbitmq//
        - CELERY_BACKEND=redis://redis:6379/0
    volumes:
        - .:/usr/src/app
    depends_on:
        - rabbitmq
        - celery

volumes:
  postgresql_data: