# Generated by Django 4.0.5 on 2022-06-26 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(blank=True, max_length=40)),
                ('game_name', models.CharField(max_length=40)),
                ('tag_line', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('champion_id', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('plain_text', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('sell', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('item_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('manaregen', 'ManaRegen'), ('healthregen', 'HealthRegen')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_map', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('puuid', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('profile_icon_id', models.CharField(blank=True, max_length=40)),
                ('summoner_level', models.CharField(blank=True, max_length=10)),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=40)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('champ_level', models.IntegerField()),
                ('lane', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('middle', 'Middle'), ('bottom', 'Bottom')], max_length=10)),
                ('teamid', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue')], max_length=4)),
                ('win', models.BooleanField(default=False, verbose_name='Venceu')),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.champion')),
                ('item0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(blank=True, max_length=40)),
                ('game_mode', models.CharField(choices=[('classic', 'Classic'), ('aram', 'Aram'), ('odin', 'Odin'), ('tutorial', 'Tutorial'), ('urf', 'Urf'), ('doombotsteemo', 'Doombotsteemo'), ('oneforall', 'Oneforall'), ('ascension', 'Ascension'), ('firstblood', 'Firstblood'), ('siege', 'Siege'), ('assassinate', 'Assassinate'), ('arsr', 'Arsr'), ('darkstar', 'Darkstar'), ('starguardian', 'Starguardian'), ('project', 'Project'), ('gamemodex', 'Gamemodex'), ('odyssey', 'Odyssey'), ('nexusblitz', 'Nexusblitz'), ('ultbook', 'Ultbook')], max_length=40)),
                ('platform_id', models.CharField(max_length=40)),
                ('map_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.map')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participant')),
            ],
        ),
    ]
