# Generated by Django 4.0.5 on 2022-06-27 21:26

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_championtag_alter_champion_champion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='item0',
        ),
        migrations.AddField(
            model_name='participant',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='app.item'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_image),
        ),
    ]
