# Generated by Django 4.0.5 on 2022-06-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_participant_item0_participant_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
