# Generated by Django 4.0.5 on 2022-06-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_map_id_match_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='platform_id',
        ),
        migrations.AddField(
            model_name='match',
            name='platform',
            field=models.CharField(choices=[('br1', 'BR1'), ('na', 'NA'), ('euw', 'EUW')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='item',
            field=models.ManyToManyField(blank=True, to='app.item'),
        ),
    ]
