# Generated by Django 4.0.5 on 2022-06-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_participant_summoner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tag_line',
            field=models.CharField(choices=[('BR1', 'BR1'), ('NA', 'NA'), ('EUW', 'EUW')], max_length=40, null=True),
        ),
    ]
