# Generated by Django 4.0.5 on 2022-06-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_account_tag_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='participant',
        ),
        migrations.AddField(
            model_name='match',
            name='participant',
            field=models.ManyToManyField(to='app.participant'),
        ),
    ]
