# Generated by Django 4.0.5 on 2022-06-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_match_participant_match_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='participant',
            field=models.ManyToManyField(max_length=10, to='app.participant'),
        ),
    ]
