# Generated by Django 4.0.5 on 2022-06-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_match_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='champion',
            name='sell',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant',
            field=models.ManyToManyField(to='app.participant'),
        ),
    ]
