# Generated by Django 4.0.5 on 2022-06-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_champion_price_alter_champion_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='id_map',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='puuid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
