# Generated by Django 4.0.5 on 2022-06-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_gamemode_alter_match_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('aram', 'Aram'), ('odin', 'Odin'), ('tutorial', 'Tutorial'), ('urf', 'Urf'), ('doombotsteemo', 'Doombotsteemo'), ('oneforall', 'Oneforall'), ('ascension', 'Ascension'), ('firstblood', 'Firstblood'), ('siege', 'Siege'), ('assassinate', 'Assassinate'), ('arsr', 'Arsr'), ('darkstar', 'Darkstar'), ('starguardian', 'Starguardian'), ('project', 'Project'), ('gamemodex', 'Gamemodex'), ('odyssey', 'Odyssey'), ('nexusblitz', 'Nexusblitz'), ('ultbook', 'Ultbook')], max_length=40, null=True),
        ),
    ]
