# Generated by Django 4.0.5 on 2022-06-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_match_game_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='plain_text',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='plain_text',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
