# Generated by Django 4.0.5 on 2022-07-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_participant_lane_alter_summoner_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='participant',
            field=models.ManyToManyField(blank=True, to='app.participant'),
        ),
    ]
