# Generated by Django 4.0.5 on 2022-07-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_match_id_match_matchid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='matchid',
        ),
    ]
